version: "3"

services:
  zoo0:
    image: zookeeper:latest
    ports:
      - 8181:2181
    environment:
      ZOO_MY_ID: 0
      ZOO_SERVERS: "server.0=0.0.0.0:2888:3888 server.1=zoo1:2888:3888 server.2=zoo2:2888:3888"
    volumes:
      - $PWD/data/zoo0/data:/data
      - $PWD/data/zoo0/datalog:/datalog
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - zookeeper

  zoo1:
    image: zookeeper:latest
    ports:
      - 8182:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: "server.0=zoo0:2888:3888 server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888"
    volumes:
      - $PWD/data/zoo1/data:/data
      - $PWD/data/zoo1/datalog:/datalog
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - zookeeper

  zoo2:
    image: zookeeper:latest
    ports:
      - 8183:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: "server.0=zoo0:2888:3888 server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888"
    volumes:
      - $PWD/data/zoo2/data:/data
      - $PWD/data/zoo2/datalog:/datalog
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - zookeeper

  zkui:
    image: cheon/zkui:latest
    ports:
      - 8090:9090
    environment:
      ZKSERVER: "zoo0:2181,zoo1:2181,zoo2:2181"
    networks:
      - zookeeper

networks:
  zookeeper:
