version: "3"

services:
  kafka0:
    image: "bitnami/kafka"
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zoo0:2181,zoo1:2181,zoo2:2181"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    volumes:
      - $PWD/data/kafka0:/bitnami/kafka
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - zookeeper

  kafka1:
    image: "bitnami/kafka"
    ports:
      - 9093:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zoo0:2181,zoo1:2181,zoo2:2181"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    volumes:
      - $PWD/data/kafka1:/bitnami/kafka
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - zookeeper

  kafka2:
    image: "bitnami/kafka"
    ports:
      - 9094:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zoo0:2181,zoo1:2181,zoo2:2181"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    volumes:
      - $PWD/data/kafka2:/bitnami/kafka
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - zookeeper

  kafka_manager:
    image: cheon/kafka-eagle:latest
    ports:
      - "8084:8084"
    environment:
      ZKSERVER: "zoo0:2181,zoo1:2181,zoo2:2181"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
    - zookeeper

networks:
  zookeeper:
